name: Deploy Sphinx Docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-deploy:
    name: Build & Deploy Docs
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build Sphinx docs
        run: sphinx-build -b html docs _build/html

      - name: Copy built docs
        run: rsync -avz _build/html/ /var/www/api-wrapper-docs/
