name: Deploy Sphinx Documentation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    name: Build & Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Sphinx dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-sphinx
      - name: Install requirements
        run: |
          cd docs
          pip install -r requirements.txt

      - name: Build Sphinx docs
        run: sphinx-build -b html docs _build/html

      - name: Copy built docs
        uses: itsneil17/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_TARGET: /var/www/api-wrapper-docs/
          RSYNC_SOURCE: _build/html/
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SSH_USERNAME}}
          SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
          SSH_PORT: 1711
